const books = [
{ name: "To Kill a Mockingbird", author: "Harper Lee", year: 1960, price: 12.99 },
  { name: "1984", author: "George Orwell", year: 1949, price: 10.50 },
  { name: "The Great Gatsby", author: "F. Scott Fitzgerald", year: 1925, price: 11.25 },
  { name: "Moby Dick", author: "Herman Melville", year: 1851, price: 14.00 },
  { name: "Pride and Prejudice", author: "Jane Austen", year: 1813, price: 9.99 },
  { name: "The Catcher in the Rye", author: "J.D. Salinger", year: 1951, price: 13.45 },
  { name: "The Hobbit", author: "J.R.R. Tolkien", year: 1937, price: 15.99 },
  { name: "Brave New World", author: "Aldous Huxley", year: 1932, price: 12.75 },
  { name: "Crime and Punishment", author: "Fyodor Dostoevsky", year: 1866, price: 16.20 },
  { name: "The Alchemist", author: "Paulo Coelho", year: 1988, price: 11.80 },
  { name: "War and Peace", author: "Leo Tolstoy", year: 1869, price: 18.50 },
  { name: "Jane Eyre", author: "Charlotte Bronte", year: 1847, price: 10.99 },
  { name: "The Lord of the Rings", author: "J.R.R. Tolkien", year: 1954, price: 25.00 },
  { name: "Animal Farm", author: "George Orwell", year: 1945, price: 8.95 },
  { name: "The Kite Runner", author: "Khaled Hosseini", year: 2003, price: 14.40 },
  { name: "The Book Thief", author: "Markus Zusak", year: 2005, price: 13.60 },
  { name: "Harry Potter and the Sorcerer's Stone", author: "J.K. Rowling", year: 1997, price: 17.99 },
  { name: "The Chronicles of Narnia", author: "C.S. Lewis", year: 1956, price: 19.99 },
  { name: "The Da Vinci Code", author: "Dan Brown", year: 2003, price: 12.49 },
  { name: "The Hunger Games", author: "Suzanne Collins", year: 2008, price: 13.99 },
  { name: "Dune", author: "Frank Herbert", year: 1965, price: 18.75 },
  { name: "Frankenstein", author: "Mary Shelley", year: 1818, price: 9.50 },
  { name: "Dracula", author: "Bram Stoker", year: 1897, price: 10.20 },
  { name: "The Shining", author: "Stephen King", year: 1977, price: 15.25 },
  { name: "Fahrenheit 451", author: "Ray Bradbury", year: 1953, price: 11.45 },
  { name: "The Road", author: "Cormac McCarthy", year: 2006, price: 14.10 },
  { name: "A Tale of Two Cities", author: "Charles Dickens", year: 1859, price: 9.75 },
  { name: "Les Miserables", author: "Victor Hugo", year: 1862, price: 20.00 },
  { name: "The Fault in Our Stars", author: "John Green", year: 2012, price: 12.30 },
  { name: "The Martian", author: "Andy Weir", year: 2011, price: 16.99 }
];

module.exports = books;
